export default function CreateASkillPage() {
  return (
    <article>
      <div className="flex items-center gap-3 mb-6">
        <span className="w-8 h-px bg-ink block" />
        <span className="font-mono text-[11px] uppercase tracking-widest text-muted">
          NarraNexus &middot; Skills &amp; Tools
        </span>
      </div>

      <h1 className="font-heading text-4xl font-800 leading-tight mb-4">
        Create a Skill
      </h1>
      <p className="text-lg font-body font-300 text-muted mb-8 max-w-2xl">
        Write a SKILL.md, host it anywhere, and NarraNexus agents can learn
        it. No code required &mdash; just clear instructions.
      </p>

      <hr className="border-rule mb-8" />

      {/* What a skill is */}
      <section className="mb-12">
        <h2 className="font-heading text-2xl font-700 mb-4">
          What Makes a Skill
        </h2>
        <p className="font-body font-300 text-sm text-muted leading-relaxed mb-4">
          A skill is a directory containing at minimum a{" "}
          <code className="font-mono text-xs px-1.5 py-0.5 bg-paper-2">
            SKILL.md
          </code>{" "}
          file. This file is the entire skill &mdash; it tells the agent
          what the skill does, what credentials it needs, and how to use it.
          The agent reads this file, follows the instructions, and internalizes
          the capability.
        </p>
        <div className="space-y-px bg-rule">
          {[
            {
              file: "SKILL.md",
              required: true,
              desc: "The skill manifest and documentation. YAML frontmatter for metadata, Markdown body for instructions.",
            },
            {
              file: ".skill_meta.json",
              required: false,
              desc: "Auto-generated by the system. Tracks installation source, study status, and credential configuration.",
            },
            {
              file: ".skill_config.json",
              required: false,
              desc: "Auto-generated. Stores saved credentials and environment variables (base64-encoded).",
            },
            {
              file: "Supporting files",
              required: false,
              desc: "Scripts, templates, examples, or data files the skill needs. Referenced from SKILL.md.",
            },
          ].map((item) => (
            <div key={item.file} className="bg-paper p-3 flex gap-6">
              <div className="w-40 shrink-0 flex items-center gap-2">
                <code className="font-mono text-xs text-ink">
                  {item.file}
                </code>
                {item.required && (
                  <span className="font-mono text-[9px] uppercase tracking-wider text-muted px-1 py-0.5 border border-rule">
                    Required
                  </span>
                )}
              </div>
              <span className="font-body font-300 text-sm text-muted">
                {item.desc}
              </span>
            </div>
          ))}
        </div>
      </section>

      {/* SKILL.md format */}
      <section className="mb-12">
        <h2 className="font-heading text-2xl font-700 mb-4">
          SKILL.md Format
        </h2>
        <p className="font-body font-300 text-sm text-muted leading-relaxed mb-4">
          The frontmatter provides metadata for discovery and dependency
          checking. The body contains the actual instructions the agent will
          read and follow.
        </p>

        <div className="border border-rule bg-paper-2/30 p-6 mb-6">
          <pre className="font-mono text-xs text-ink leading-relaxed whitespace-pre-wrap">{`---
name: "my-skill"
description: "What this skill does in one sentence"
version: "1.0.0"
author: "Your Name"
metadata:
  clawdbot:
    requires:
      env: ["API_KEY", "API_SECRET"]
      bins: ["python", "curl"]
---

# My Skill

## What It Does
Describe the capability this skill provides...

## Setup
1. Go to https://example.com and create an account
2. Generate an API key from the settings page
3. Save the key (the agent will store it automatically)

## Usage
Explain how to use the skill in conversation...

## API Reference
Document the endpoints or commands the agent will use...`}</pre>
        </div>

        <h3 className="font-heading text-base font-600 mb-3">
          Frontmatter Fields
        </h3>
        <div className="space-y-px bg-rule">
          {[
            { field: "name", desc: "Unique identifier for the skill (used as directory name)" },
            { field: "description", desc: "One-line description shown in skill listings" },
            { field: "version", desc: "Semantic version for update detection" },
            { field: "author", desc: "Creator name or organization" },
            { field: "requires.env", desc: "List of environment variable names the skill needs (e.g., API_KEY)" },
            { field: "requires.bins", desc: "List of binary dependencies (e.g., python, curl, node)" },
          ].map((item) => (
            <div key={item.field} className="bg-paper p-3 flex gap-6">
              <code className="font-mono text-xs text-ink w-28 shrink-0">
                {item.field}
              </code>
              <span className="font-body font-300 text-sm text-muted">
                {item.desc}
              </span>
            </div>
          ))}
        </div>
      </section>

      {/* Writing good instructions */}
      <section className="mb-12">
        <h2 className="font-heading text-2xl font-700 mb-4">
          Writing Good Instructions
        </h2>
        <p className="font-body font-300 text-sm text-muted leading-relaxed mb-4">
          The agent is reading your SKILL.md as-is. The quality of the skill
          depends entirely on how clearly you write the instructions:
        </p>
        <div className="space-y-px bg-rule">
          {[
            {
              tip: "Be explicit about setup steps",
              desc: "Don\u2019t assume the agent knows how to register on your platform. Walk through every step: URL to visit, fields to fill, where to find the API key.",
            },
            {
              tip: "Specify credential names",
              desc: "Use consistent environment variable names (API_KEY, not api-key or apiKey). Declare them in the frontmatter requires.env so the system can track them.",
            },
            {
              tip: "Include error handling",
              desc: "Document common errors and what to do. If an API returns 401, tell the agent to check if the key is expired.",
            },
            {
              tip: "Document recurring tasks",
              desc: "If the skill needs periodic work (e.g., check for updates daily), include a HEARTBEAT.md or describe the schedule clearly. The agent will use job_create to set it up.",
            },
            {
              tip: "Test with a fresh agent",
              desc: "Before publishing, have a new agent study your skill from scratch. Watch for ambiguity, missing steps, or assumptions about prior knowledge.",
            },
          ].map((item) => (
            <div key={item.tip} className="bg-paper p-5">
              <span className="font-heading text-sm font-700">
                {item.tip}
              </span>
              <p className="font-body font-300 text-sm text-muted mt-1 leading-relaxed">
                {item.desc}
              </p>
            </div>
          ))}
        </div>
      </section>

      {/* Hosting and publishing */}
      <section className="mb-12">
        <h2 className="font-heading text-2xl font-700 mb-4">
          Hosting &amp; Publishing
        </h2>
        <p className="font-body font-300 text-sm text-muted leading-relaxed mb-4">
          Skills can be hosted anywhere accessible via a public URL:
        </p>
        <div className="space-y-px bg-rule">
          {[
            {
              method: "Your website",
              desc: "Host SKILL.md at any URL. Users tell their agent: \"Learn the skill at https://yoursite.com/skill.md\"",
            },
            {
              method: "GitHub",
              desc: "Push to a public repo with SKILL.md in the root. Agents can clone it directly.",
            },
            {
              method: "ClawHub",
              desc: "Publish to the community marketplace for wider discovery. Users install by slug via the clawhub CLI.",
            },
          ].map((item) => (
            <div key={item.method} className="bg-paper p-4 flex gap-6">
              <span className="font-heading text-sm font-700 w-28 shrink-0">
                {item.method}
              </span>
              <span className="font-body font-300 text-sm text-muted">
                {item.desc}
              </span>
            </div>
          ))}
        </div>
      </section>

      {/* Link to Learn a Skill for the study process */}
      <section>
        <p className="font-body font-300 text-sm text-muted leading-relaxed">
          For what happens when an agent studies your skill, see{" "}
          <a
            href="/docs/tools/learn-a-skill"
            className="font-500 text-ink underline"
          >
            Learn a Skill
          </a>
          .
        </p>
      </section>
    </article>
  );
}
